import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ".././globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import { MenuItem } from "@/types/MenuItem";
import {
  LayoutDashboard,
  ClipboardList,
  BookOpen,
  BarChart2,
  LogOut,
  BookUser
} from 'lucide-react'

const menuItems: MenuItem[] = [
  {
    name: 'Dashboard',
    route: '/l&d',
    icon: <LayoutDashboard size={24} />
  },
  {
    name: 'Training Requests',
    route: '/l&d/training-requests',
    icon: <ClipboardList size={24} />
  },
  {
    name: 'Reports & Analytics',
    route: '/l&d/analytics',
    icon: <BarChart2 size={24} />
  },
  {
    name: 'Add Course',
    route: '/l&d/add-course',
    icon: <BookUser size={24} />
  },
  {
    name: 'Course Catalog',
    route: '/l&d/courses',
    icon: <BookOpen size={24} />
  },
  {
    name: 'Log Out',
    route: 'l&d/logout',
    icon: <LogOut size={24} />
  }
]



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Sidebar menuItems={menuItems}>
          {children}
        </Sidebar>
      </body>
    </html>
  );
}
